module.exports = Grunt;

function Grunt(grunt) {

	var Configuration = {};
	Configuration.package = grunt.file.readJSON('package.json');

	require('jit-grunt')(grunt, {
		'babel': 'grunt-babel',
		'add_comment': 'grunt-add-comment',
		'jasmine_nodejs': 'grunt-jasmine-nodejs'
	});

	Configuration.babel = {
		dist: {
			options: {
				sourceMap: false
			},
			files: [{
				expand: true,
				ext: '.js',
				src: ['lib/**/*.es6','specs/**/*.es6']
			}]
		}
	};

	Configuration.add_comment = {
		common: {
			options: {
				comments: ['Autogenerated, do not edit. All changes will be undone.'],
				prepend: true,
				syntaxes: {
					'.js': '//'
				}
			},
			files: [{
				expand: true,
				src: ['lib/**/*.js','specs/**/*.js']
			}]
		}
	};

	Configuration.jasmine_nodejs = {
		options: {
			specNameSuffix: '.js',
			useHelpers: false,
			reporters: {
				console: {
					colors: true,
					cleanStack: 1,
					verbosity: 3,
					listStyle: 'indent',
					activity: true
				}
			}
		},
		chikorita: {
			specs: ['specs/**']
		}
	};

	grunt.initConfig(Configuration);
	grunt.registerTask('es6', ['babel:dist', 'add_comment']);
	grunt.registerTask('unit', ['jasmine_nodejs:chikorita']);
}